language: go
go:
  - tip
before_install:
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/stretchr/testify/assert
  - go get github.com/Sirupsen/logrus
  - go get github.com/spf13/viper
  - go get github.com/tuvistavie/securerandom
  - go get gopkg.in/mattes/go-expand-tilde.v1
  - go get github.com/akamai-open/AkamaiOPEN-edgegrid-golang
install:
  - go install .
script:
  - export PATH="$PATH:$HOME/gopath/bin"
  - cp $HOME/gopath/src/github.com/akamai-open/AkamaiOPEN-edgegrid-golang/sample_edgerc $HOME/.edgerc
